Db:
  Provider: sqlite # sqlite, sqlserver, postgresql
  ConnectionString: "Data Source=app_data/data.db"

Authentication:
  AuthorityUrl: "http://users.localtest.me:8181"
  Schema: houseapi
  ApiName: houseapi
  ApiSecret: "@KiHRt7Uj0zssPlg2YvffMsUEd"
  DisableRequireHttpsMetadata: true
MQTT:
  Server: mqtt.localtest.me
  DefaultTopic: local/house/sensor/reading
  Port: 1883
  NewReadingTopic: local/house/sensor/reading
  UnknownDeviceTopic: local/house/devices/unknown


Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information

Kestrel:
  Endpoints:
    HTTP:
      Url: http://*:8080
#    HTTPS:
#      Url: https://*:8443
#      Certificate:
#        Path: app_config/house.dev.local.pfx
#        Password: "@Password1"
