Db:
  Provider: sqlite # sqlite, mysql, sqlserver, postgresql
  ConnectionString: "Data Source=app_data/data.db"

Client:
  DevicesBaseUrl: "http://gateway"

Authentication:
  AuthorityUrl: "http://house.dev.local"
  ApiName: houseapi
  DisableRequireHttpsMetadata: true

Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information

Kestrel:
  Endpoints:
    HTTP:
      Url: http://*:8080
#    HTTPS:
#      Url: https://*:8443
#      Certificate:
#        Path: app_config/house.dev.local.pfx
#        Password: "@Password1"
