version: '3.6'

services:
  gateway:
    image: ${DOCKER_REGISTRY}house.gateway:beta
    networks:
      housenet:
        aliases:
          - "gateway.house.dev.local"
    ports:
      - "80:80"
      - "443:443"
    user: "${USER}"
    depends_on:
      - users
      - devices

  users:
    image: ${DOCKER_REGISTRY}house.users:beta
    networks: 
      housenet:
        aliases:
          - "house.dev.local"
    user: "${USER}"
    ports:
      - "8082:80"

  devices:
    image: ${DOCKER_REGISTRY}house.devices:beta
    networks:
      housenet:
        aliases:
          - "devices.house.dev.local"
    user: "${USER}"
    ports:
      - "8080:80"
    depends_on:
      - users

  sensorlogging:
    image: ${DOCKER_REGISTRY}${ImageName}:${BuildType}-${SANNEL_VERSION}-${SANNEL_ARCH}
    build:
      context: .
      dockerfile: src/Sannel.House.SensorLogging/Dockerfile
      args:
        USER: "${USER}"
    networks:
      housenet:
        aliases:
          - "sensorlogging.house.dev.local"
    user: "${USER}"
    ports:
      - "8084:80"
    depends_on:
      - users
      - devices
      - gateway


networks:
  housenet: