version: '3.6'

services:
  users:
    image: ${DOCKER_REGISTRY}sannelhouseusers:beta
    networks: 
      housenet:
        aliases:
          - "users.house.dev.local"
    ports:
      - "443:443"

  devices:
    image: ${DOCKER_REGISTRY}sannelhousedevices:beta-v1
    networks:
      housenet:
        aliases:
          - "devices.house.dev.local"
    ports:
      - "80444:443"
    depends_on:
      - users

  tests:
    image: ${DOCKER_REGISTRY}sannelhousesensorentries:tests-${SANNEL_ARCH}
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: src/Sannel.House.SensorLogging.Tests/Dockerfile
    networks:
      - housenet

  sensorlogging:
    image: ${DOCKER_REGISTRY}sannelhousesensorentries:${SANNEL_VERSION}-beta-${SANNEL_ARCH}
    build:
      context: .
      dockerfile: src/Sannel.House.SensorLogging/Dockerfile
      args:
        USER: "${USER}"
    networks:
      housenet:
        aliases:
          - "sensorlogging.house.dev.local"
    ports:
      - "80443:443"
    depends_on:
      - users
      - devices


networks:
  housenet: