version: '3.6'

services:
  users:
    image: ${DOCKER_REGISTRY}house.users:beta
    networks: 
      housenet:
        aliases:
          - "users.house.dev.local"
    ports:
      - "443:443"

  devices:
    image: ${DOCKER_REGISTRY}house.devices:beta
    networks:
      housenet:
        aliases:
          - "devices.house.dev.local"
    ports:
      - "80444:443"
    depends_on:
      - users

  sensorlogging:
    image: ${DOCKER_REGISTRY}${ImageName}:${BuildType}-${SANNEL_VERSION}-${SANNEL_ARCH}
    build:
      context: .
      dockerfile: src/Sannel.House.SensorLogging/Dockerfile
      args:
        USER: "${USER}"
    networks:
      housenet:
        aliases:
          - "sensorlogging.house.dev.local"
    ports:
      - "80443:443"
    depends_on:
      - users
      - devices


networks:
  housenet: